# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 250, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 58, 21))
        self.label.setObjectName("label")
        self.player1name = QtWidgets.QLineEdit(Dialog)
        self.player1name.setGeometry(QtCore.QRect(100, 10, 113, 21))
        self.player1name.setObjectName("player1name")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 58, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 58, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 58, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 170, 58, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 210, 58, 21))
        self.label_6.setObjectName("label_6")
        self.player2name = QtWidgets.QLineEdit(Dialog)
        self.player2name.setGeometry(QtCore.QRect(100, 50, 113, 21))
        self.player2name.setObjectName("player2name")
        self.player4name = QtWidgets.QLineEdit(Dialog)
        self.player4name.setGeometry(QtCore.QRect(100, 130, 113, 21))
        self.player4name.setObjectName("player4name")
        self.player3name = QtWidgets.QLineEdit(Dialog)
        self.player3name.setGeometry(QtCore.QRect(100, 90, 113, 21))
        self.player3name.setObjectName("player3name")
        self.player5name = QtWidgets.QLineEdit(Dialog)
        self.player5name.setGeometry(QtCore.QRect(100, 170, 113, 21))
        self.player5name.setObjectName("player5name")
        self.player6name = QtWidgets.QLineEdit(Dialog)
        self.player6name.setGeometry(QtCore.QRect(100, 210, 113, 21))
        self.player6name.setObjectName("player6name")
        self.player1computer = QtWidgets.QCheckBox(Dialog)
        self.player1computer.setGeometry(QtCore.QRect(280, 10, 85, 21))
        self.player1computer.setObjectName("player1computer")
        self.player2computer = QtWidgets.QCheckBox(Dialog)
        self.player2computer.setGeometry(QtCore.QRect(280, 50, 85, 21))
        self.player2computer.setObjectName("player2computer")
        self.player3computer = QtWidgets.QCheckBox(Dialog)
        self.player3computer.setGeometry(QtCore.QRect(280, 90, 85, 21))
        self.player3computer.setObjectName("player3computer")
        self.player4computer = QtWidgets.QCheckBox(Dialog)
        self.player4computer.setGeometry(QtCore.QRect(280, 130, 85, 21))
        self.player4computer.setObjectName("player4computer")
        self.player5computer = QtWidgets.QCheckBox(Dialog)
        self.player5computer.setGeometry(QtCore.QRect(280, 170, 85, 21))
        self.player5computer.setObjectName("player5computer")
        self.player6computer = QtWidgets.QCheckBox(Dialog)
        self.player6computer.setGeometry(QtCore.QRect(280, 210, 85, 21))
        self.player6computer.setObjectName("player6computer")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Player settings"))
        self.label.setText(_translate("Dialog", "Player1:"))
        self.label_2.setText(_translate("Dialog", "Player2:"))
        self.label_3.setText(_translate("Dialog", "Player3:"))
        self.label_4.setText(_translate("Dialog", "Player4:"))
        self.label_5.setText(_translate("Dialog", "Player5:"))
        self.label_6.setText(_translate("Dialog", "Player6:"))
        self.player1computer.setText(_translate("Dialog", "Computer"))
        self.player2computer.setText(_translate("Dialog", "Computer"))
        self.player3computer.setText(_translate("Dialog", "Computer"))
        self.player4computer.setText(_translate("Dialog", "Computer"))
        self.player5computer.setText(_translate("Dialog", "Computer"))
        self.player6computer.setText(_translate("Dialog", "Computer"))
